# Generated by Django 2.2.5 on 2021-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210210_1842'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='room',
        ),
        migrations.AddField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(blank=True, to='rooms.Room'),
        ),
    ]
